apiVersion: v1
kind: PersistentVolume
metadata:
  name: dongliyuan-pc-webapps
  namespace: dpc  
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  nfs:
    path: /mnt/dpc/dongliyuan-pc-webapps
    server: 192.168.88.109
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dongliyuan-pc-webapps
  namespace: dpc  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: dongliyuan-pc-webapps
---
apiVersion: v1
kind: Service
metadata:
  name: dongliyuan-pc
  namespace: dpc  
  labels:
    app: dongliyuan-pc
spec:
  type: NodePort  
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 10502
    name: dongliyuan-pc
  selector:
    app: dongliyuan-pc
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dongliyuan-pc
  namespace: dpc
spec:
  selector:
    matchLabels:
      app: dongliyuan-pc
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dongliyuan-pc
    spec:
      containers:
      - name: dongliyuan-pc
        image: registry.tongxin.dpc.com/tomcat:8.5
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dongliyuan-pc-webapps
          mountPath: /usr/local/tomcat/webapps   
      volumes:                     
        - name: dongliyuan-pc-webapps
          persistentVolumeClaim:
            claimName: dongliyuan-pc-webapps        