apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-nodeport
  namespace: dpc  
  labels:
    app: kafka-cluster-nodeport
spec:
  ports:
  - port: 9092
    nodePort: 19092
    name: kafka
  selector:
    app: kafka-cluster
  type: NodePort