apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql56-nodeport
  name: mysql56-nodeport
  namespace: dpc
spec:
  clusterIP: 10.100.208.235
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql56
    nodePort: 33307
    port: 3307
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql56
  sessionAffinity: None
  type: NodePort