apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql56-config
  namespace: dpc-xiongan-test
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    default_authentication_plugin=mysql_native_password
    lower_case_table_names=1
    default-time-zone=+8:00
    innodb_flush_log_at_trx_commit=0
    innodb_autoextend_increment=128M
    innodb_log_buffer_size=16M
    innodb_log_file_size=128M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql56-data-dpc-xiongan-test
  namespace: dpc-xiongan-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /mnt/dpc-xiongan-test/mysql56-data
    server: 192.168.88.109
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql56-data
  namespace: dpc-xiongan-test  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: mysql56-data-dpc-xiongan-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: dpc-xiongan-test  
  name: mysql56
  labels:
    app: mysql56
spec:
  selector:
    app: mysql56  
  ports:
    - protocol: TCP
      nodePort: 33308    
      port: 3306
      targetPort: 3306
      name: mysql56
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql56
  namespace: dpc-xiongan-test
spec:
  selector:
    matchLabels:
      app: mysql56 # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql56 # has to match .spec.selector.matchLabels
    spec:                   
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql56
        image: registry.tongxin.dpc.com/mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql56
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: qwer1234
        volumeMounts:
        - name: mysql56-config
          mountPath: /etc/mysql/conf.d
        - name: mysql56-data
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql56-config
          configMap:
            name: mysql56-config 
        - name: mysql56-data
          persistentVolumeClaim:
            claimName: mysql56-data

