apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-dpc-xiongan-test
  namespace: dpc-xiongan-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/dpc-xiongan-test/rabbitmq/rabbitmq-data
    server: 192.168.88.109
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: dpc-xiongan-test  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: rabbitmq-data-dpc-xiongan-test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-config-dpc-xiongan-test
  namespace: dpc-xiongan-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/dpc-xiongan-test/rabbitmq/rabbitmq-config
    server: 192.168.88.109
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-config
  namespace: dpc-xiongan-test  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: rabbitmq-config-dpc-xiongan-test  
---
apiVersion: v1
kind: Service
metadata:
  namespace: dpc-xiongan-test  
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq  
  ports:
    - protocol: TCP
      port: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      nodePort: 15674
      name: rabbitmq-web
  type: NodePort 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: dpc-xiongan-test
spec:
  selector:
    matchLabels:
      app: rabbitmq # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: rabbitmq # has to match .spec.selector.matchLabels
    spec:                   
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: registry.tongxin.dpc.com/rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672